### ISSUE TITLE
Error when start  "npm run start"

### ISSUE THREAD

**Issue by eosvn** [leduyminh48/nestjs-oauth2-example#1]
```
[Nest] 5570   - 09/14/2021, 3:57:24 PM   [NestFactory] Starting Nest application...
[Nest] 5570   - 09/14/2021, 3:57:25 PM   [InstanceLoader] TypeOrmModule dependencies initialized +137ms
[Nest] 5570   - 09/14/2021, 3:57:25 PM   [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 5570   - 09/14/2021, 3:57:25 PM   [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:25 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +1196ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] AuthorizationCodeModule dependencies initialized +1ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] AccessTokenModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] ClientModule dependencies initialized +1ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [InstanceLoader] UserModule dependencies initialized +0ms
[Nest] 5570   - 09/14/2021, 3:57:26 PM   [ExceptionHandler] Cannot read property 'split' of undefined +2ms
TypeError: Cannot read property 'split' of undefined
    at new OidcProviderService (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/dist/src/oidc/oidc-provider.service.js:26:59)
    at Injector.instantiateClass (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/injector.js:286:19)
    at callback (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/injector.js:42:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Injector.resolveConstructorParams (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/injector.js:114:24)
    at async Injector.loadInstance (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/injector.js:46:9)
    at async Injector.loadProvider (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/injector.js:68:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
    at async /Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/instance-loader.js:28:13
    at async Promise.all (index 15)
    at async InstanceLoader.createInstances (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/instance-loader.js:27:9)
    at async InstanceLoader.createInstancesOfDependencies (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/injector/instance-loader.js:17:9)
    at async /Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/nest-factory.js:90:17
    at async Function.asyncRun (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/errors/exceptions-zone.js:18:13)
    at async NestFactoryStatic.initialize (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/nest-factory.js:88:13)
    at async NestFactoryStatic.create (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/node_modules/@nestjs/core/nest-factory.js:34:9)
    at async bootstrap (/Volumes/BeTai512G/Downloads/nestjs-oauth2-example-main/dist/src/main.js:9:17)
```

**Comment by leduyminh48** [comment]
Please follow this guide on how to setup your environment. The issue here is you didnt have SECURE_KEY env variable setup. Will work on improving the error log
https://github.com/leduyminh48/nestjs-oauth2-example#how-to-test-this-servers-authorization_code-flow

**Comment by eosvn** [comment]
Thank you so much!
